name: Dev CI
on: 
  push:
    branches: [ demo-dev ]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root_pass
          MYSQL_DATABASE: laravel
        ports:
          - 3306:3306

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Build project
        run: echo "Building project..."
